from django.urls import path
from practice.views import *

urlpatterns=[
    path('index',index,name='index'),
    path('save',save,name='save'),
    path('check',check,name='check'),
    path('signup',signup,name='signup'),
    path('home1',home1,name='home1'),
    # path('create',createcookie,name='cookie'),
    # path('checkc',checkcookie,name='checkc'),
    # path('creates',createsession,name='cookies'),
    # path('checks',checksession,name='checks'),
    # path('logout',logout,name='logout'),
    # path('captcha',captcha,name='captcha'),
    path('attendance',attendance,name='attendance'),
    path('teacher',teacher,name='teacher'),
    path('deleteS',deleteS,name='deleteS'),
    path('updateS',updateS,name='updateS'),
    path('updateSR',updateSR,name='updateSR'),
    path('upsave',upsave,name='upsave'),
    path('upsaveSR',upsaveSR,name='upsaveSR'),
    path('assign',assign,name='assign'),
    path('formmm',formmm,name='formmm'),
    path('insert',insert,name='insert'),
    path('profile',profile,name='profile'),
    path('ajax',ajax2,name='ajax'),
    path("result",result,name='result'),
    path('ajax2res',ajax2res,name='ajax2res'),
    path('tlogin',tlogin,name='tlogin'),
    path('fees',fees,name='fees'),
    path('tcheck',tcheck,name='tcheck'),
    path('tsave',tsave,name='tsave'),
    path('ss',ss,name='ss'),
    path('upattend',upattend,name='upattend'),
    path('attendsave',attendsave,name='attendsave'),
    path("logout",logout,name="logout"),
    path("tlogout",tlogout,name="tlogout"),
]